### PR TITLE
React + Firebase

### PR DESCRIPTION
**Pull request by robinandeer**
:warning: Just demoing some code, I don't mean for this PR to be merged!

---

During the [EBOSS](http://www.scilifelab.se/research/open-source-projects/) meeting we discussed ideas for the future of this site. To realize them, we will need to incorporate some additional technologies (unless we are to make the move to a CMS :stuck_out_tongue_closed_eyes:). I would certainly consider setting up a Heroku instance with a backend Python server, however. But let's see what's possible with a static web app.

I've put together a very quick (and dirty) example using [Firebase](https://www.firebase.com/) for a database layer and [React](https://facebook.github.io/react/) for UI and interaction. All you need is to start the server and go to `http://localhost:4000/react/`. This will load projects from Firebase and render them using React. The tight integration is pretty sweet :smile:

Please let me know if I'm alone in thinking this is a solution worth considering :sweat_smile:

### CODE REVIEW

**Comment by robinandeer** [comment]
Just added the dynamic loading of GitHub stars for each repository. It just works. There's something about this React :smiley:

**Comment by ewels** [comment]
So the idea is that the content of the site is stored on the React servers? Are we going to max out the free price plan with this?

Super clean code :grinning:

**Comment by robinandeer** [comment]
Thank you! React is totally all about components which is awesome.

We would in this example use Firebase as a normal database (I assume this is what you meant) but access it directly from the client side. The free plan I believe will at least get us far enough :smiley:

Exited? A little?

ps. Can I really edit your comment? Crazy... d.s

**Comment by ewels** [comment]
Ok, nice! How do we add content to the database?

Excited, but a little wary :wink:

**Comment by robinandeer** [comment]
I've sent an invite to the database editor. They have an API which you can read about here: https://www.firebase.com/docs/web/

You have to check out the automatic updating that happens on the website as soon as value in the database is changed. Not super useful but still so cool.

This is still more of an experiment than anything I'm seriously suggesting we implement.

**Comment by ewels** [comment]
Ok, nice - so could we write a back end page for adding / editing projects? Could tie this to github authentication, giving anyone who appears in the developers table write access..

I'm getting more excited by the minute :smile:

**Comment by robinandeer** [comment]
Yay!

I think everything will come down to what we feel most comfortable with. It's not terribly difficult to setup a Heroku instance if we need a proper Python backend for example.

I have otherwise started looking into hosted form services (see #35) that could be integrated directly into React. Although I'm not sure how we will deal with secret keys etc. :sweat_smile:

**Comment by ewels** [comment]
Yup, agreed. As long as we have a simple user interface (preferably which doesn't require people to run anything locally) then I'm happy. Stuff like GitHub auth would be a bonus.

Why do we need a hosted form service - can't we just create a HTML/js form on the site which is protected by some kind of authentication, which posts to React? Keep everything within the one site?

Can put secret keys in an included file and then `.gitignore` it..

**Comment by robinandeer** [comment]
I guess we could get away with just a plain HTML/JS form solution. The cloud solutions might help out again with authentication (like using Google Forms).

According security: the problem that I don't know a quick fix for is that all secret keys need to be available from the frontend (JS) which essentially means anyone that knows how to open the developer console will get access to the keys. But I should read up on that.

**Comment by ewels** [comment]
Ah I see, yeah that probably wouldn't be super secure.. :)

**Comment by guillermo-carrasco** [comment]
@robinandeer @ewels what should we do with this PR? I was just reviewing pending PRs and saw this one. You've decided to go with WordPress finally, right?

**Comment by ewels** [comment]
Yup, I think probably close it and leave the branch open for reference as it's cool..

**Comment by robinandeer** [comment]
:cry:

But I'm super happy about the very fast progress on the WP site --- looks great! I'll refactor and compile the styles for you today @ewels!

**Pull request closed without merging**
