### PR TITLE
Fix annoying stuff

### PR DESCRIPTION
**Pull request by robinandeer**
This PR just resolves a few things that has been annoying me for a while now, hehe:

- An updates site description (mostly copied from SciLifeLab website)
- New link to "complete example" in CONCOCT so Travis will succeed again! No more red badge :stuck_out_tongue_closed_eyes:
- Fix strange layout reference

### CODE REVIEW

**Comment by guillermo-carrasco** [comment]
Yay :-)

**Comment by robinandeer** [comment]
``#78 passed`` - woho! Merge ASAP :+1:

**Comment by senthil10** [comment]
@robinandeer : There you go :)

**Comment by robinandeer** [comment]
Thank you @senthil10! Now I can drop that from my focus ^^

**Pull request merged**
